import localFont from "next/font/local";
import "./globals.css";

const airbnbCereal = localFont({
  src: [
    {
      path: "./fonts/english/AirbnbCereal_W_Lt.otf",
      weight: "300",
      style: "normal",
    },
    {
      path: "./fonts/english/AirbnbCereal_W_Bk.otf",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/english/AirbnbCereal_W_Md.otf",
      weight: "500",
      style: "normal",
    },
    {
      path: "./fonts/english/AirbnbCereal_W_Bd.otf",
      weight: "700",
      style: "normal",
    },
    {
      path: "./fonts/english/AirbnbCereal_W_XBd.otf",
      weight: "800",
      style: "normal",
    },
    {
      path: "./fonts/english/AirbnbCereal_W_Blk.otf",
      weight: "900",
      style: "normal",
    },
  ],
  variable: "--font-airbnb-cereal",
  display: "swap", // Prevents FOUT (Flash of Unstyled Text)
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${airbnbCereal.variable} antialiased`}>{children}</body>
    </html>
  );
}
